some nice updates
dreipunktnull/dhl-shipment-tracking pull request #2
Opened 2018-10-26 19:51 UTC by tabsl

use guzzle
improve data response
add d-get-signature
documentation

2018-10-29 08:20 UTC, cedricziel requested changes
Thx for your contribution - that's really some nice changes you got there.

Please adjust the doccomments so we know the types that are exchanged and remove empty class headers as mentioned.

Thx!

2018-10-29 08:20 UTC, cedricziel commented on src/Credentials.php
> +/**
Can you please remove the empty class headers? Nobody needs those...

2018-10-29 08:20 UTC, cedricziel commented on src/Credentials.php
> +     * The constructor ...
Remove comment header pls

2018-10-29 08:20 UTC, cedricziel commented on src/RequestBuilder.php
> + * Class RequestBuilder
Same here

2018-10-29 08:20 UTC, cedricziel commented on src/ShipmentTracking.php
> +     * @param        $operation
When adding doc comments, please also add the types

2018-10-29 08:20 UTC, cedricziel commented on src/ShipmentTracking.php
> +     * @return mixed
Why is the type mixed? What is returned?

2018-10-29 08:20 UTC, cedricziel commented on src/ShipmentTracking.php
> +        $xml = simplexml_load_string($xml);
Can we please also require `"ext-simplexml": "*"` in composer.json?

2018-10-29 08:20 UTC, cedricziel commented on src/ShipmentTracking.php
> +     * @param $xml
Please adjust the doccomment so it matches the reality or discard it

2018-11-03 09:51 UTC, tabsl commented
done ...

2018-11-09 14:22 UTC, tabsl commented
Any updates?

2019-01-04 08:29 UTC, proudcommerce commented
Any updates?

2019-01-04 09:02 UTC, cedricziel approved these changes

2019-01-04 09:04 UTC, merged

2019-01-04 09:05 UTC, cedricziel commented
Thank you, @tabsl !